### ISSUE TITLE
NeuralNetBinaryClassifier fails with GridSearchCV and roc_auc

### ISSUE THREAD

**Issue by dfdazac** [dnouri/skorch#442]
I'm training a binary classifier with GridSearchCV, using `roc_auc` as the scoring function. It starts fine but after finishing the last epoch, it throws an error.

If I change the scoring to `accuracy`, it runs fine.

A minimal code to reproduce this is here:

```python
import numpy as np
from torch import nn
from sklearn.datasets import make_classification
from sklearn.model_selection import GridSearchCV
from skorch.classifier import NeuralNetBinaryClassifier

X, y = make_classification(1000, 20, n_informative=10, random_state=0)
X = X.astype(np.float32)
y = y.astype(np.float32)

class MyModule(nn.Module):
    def __init__(self):
        super(MyModule, self).__init__()
        self.dense0 = nn.Linear(20, 1)

    def forward(self, X, **kwargs):
        X = self.dense0(X).squeeze()
        return X

net = NeuralNetBinaryClassifier(MyModule)
params = {'lr': [0.01, 0.02]}
gs = GridSearchCV(net, params, refit=False, cv=3, scoring='roc_auc')
gs.fit(X, y)
print(gs.best_score_, gs.best_params_)
```

And the traceback is this:

```
Traceback (most recent call last):
  File "/home/ddaza/miniconda3/envs/pygeomtf/lib/python3.6/site-packages/sklearn/metrics/scorer.py", line 182, in __call__
    y_pred = clf.decision_function(X)
AttributeError: 'NeuralNetBinaryClassifier' object has no attribute 'decision_function'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "ex.py", line 23, in <module>
    gs.fit(X, y)
  File "/home/ddaza/miniconda3/envs/pygeomtf/lib/python3.6/site-packages/sklearn/model_selection/_search.py", line 722, in fit
    self._run_search(evaluate_candidates)
  File "/home/ddaza/miniconda3/envs/pygeomtf/lib/python3.6/site-packages/sklearn/model_selection/_search.py", line 1191, in _run_search
    evaluate_candidates(ParameterGrid(self.param_grid))
  File "/home/ddaza/miniconda3/envs/pygeomtf/lib/python3.6/site-packages/sklearn/model_selection/_search.py", line 711, in evaluate_candidates
    cv.split(X, y, groups)))
  File "/home/ddaza/miniconda3/envs/pygeomtf/lib/python3.6/site-packages/sklearn/externals/joblib/parallel.py", line 917, in __call__
    if self.dispatch_one_batch(iterator):
  File "/home/ddaza/miniconda3/envs/pygeomtf/lib/python3.6/site-packages/sklearn/externals/joblib/parallel.py", line 759, in dispatch_one_batch
    self._dispatch(tasks)
  File "/home/ddaza/miniconda3/envs/pygeomtf/lib/python3.6/site-packages/sklearn/externals/joblib/parallel.py", line 716, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/home/ddaza/miniconda3/envs/pygeomtf/lib/python3.6/site-packages/sklearn/externals/joblib/_parallel_backends.py", line 182, in apply_async
    result = ImmediateResult(func)
  File "/home/ddaza/miniconda3/envs/pygeomtf/lib/python3.6/site-packages/sklearn/externals/joblib/_parallel_backends.py", line 549, in __init__
    self.results = batch()
  File "/home/ddaza/miniconda3/envs/pygeomtf/lib/python3.6/site-packages/sklearn/externals/joblib/parallel.py", line 225, in __call__
    for func, args, kwargs in self.items]
  File "/home/ddaza/miniconda3/envs/pygeomtf/lib/python3.6/site-packages/sklearn/externals/joblib/parallel.py", line 225, in <listcomp>
    for func, args, kwargs in self.items]
  File "/home/ddaza/miniconda3/envs/pygeomtf/lib/python3.6/site-packages/sklearn/model_selection/_validation.py", line 568, in _fit_and_score
    test_scores = _score(estimator, X_test, y_test, scorer, is_multimetric)
  File "/home/ddaza/miniconda3/envs/pygeomtf/lib/python3.6/site-packages/sklearn/model_selection/_validation.py", line 605, in _score
    return _multimetric_score(estimator, X_test, y_test, scorer)
  File "/home/ddaza/miniconda3/envs/pygeomtf/lib/python3.6/site-packages/sklearn/model_selection/_validation.py", line 635, in _multimetric_score
    score = scorer(estimator, X_test, y_test)
  File "/home/ddaza/miniconda3/envs/pygeomtf/lib/python3.6/site-packages/sklearn/metrics/scorer.py", line 192, in __call__
    if y_pred.shape[1] == 2:
IndexError: tuple index out of range
```

**Comment by BenjaminBossan** [comment]
Thank you for taking the time of creating a minimal example.

So the issue here is that sklearn expects a 2-dim output, which clashes with what torch expects for BCE. This is the best workaround that I found:

```python
from sklearn.metrics import roc_auc_score

def my_auc(net, X, y):
    y_proba = net.predict_proba(X)
    return roc_auc_score(y, y_proba)
...
gs = GridSearchCV(net, params, refit=False, cv=3, scoring=my_auc)
```

I hope this works for you. Please leave this open for now since we should about what skorch can do to help here.

**Comment by ottonemo** [comment]
It seems as though the behaviour of sklearn is not consistent here (or at least there are two code paths taken). If I use the ROC AuC scorer with the `y` and the output of `net.predict_proba(X)` everything works fine, only when used in conjunction with `GridSearchCV` (and possibly our scoring, not tested though) it throws the error mentioned above. Digging deeper it seems that `make_scorer` is the culprit. Minimal example:

```python

import numpy as np
from torch import nn
from sklearn.datasets import make_classification
from sklearn.model_selection import GridSearchCV
from skorch.classifier import NeuralNetBinaryClassifier

X, y = make_classification(1000, 20, n_informative=10, random_state=0)
X = X.astype(np.float32)
y = y.astype(np.float32)

class MyModule(nn.Module):
    def __init__(self):
        super(MyModule, self).__init__()
        self.dense0 = nn.Linear(20, 1)

    def forward(self, X, **kwargs):
        X = self.dense0(X).squeeze()
        return X

net = NeuralNetBinaryClassifier(MyModule)
params = {'lr': [0.01, 0.02]}

net.fit(X, y)

from sklearn.metrics import roc_auc_score, make_scorer

roc_auc_score_2 = make_scorer(roc_auc_score, needs_threshold=True)

y_pred = net.predict_proba(X)

print(roc_auc_score(y, y_pred))
print(roc_auc_score_2(net, X, y))
```

The line
```python
make_scorer(roc_auc_score, needs_threshold=True)
```
is the line that sklearn uses to create the scorer during grid search. Setting `need_threshold` to `False` solves the problem. I haven't dug deeper but I wanted to share my findings so far.

**Comment by BenjaminBossan** [comment]
I wonder if it makes any sense to find a workaround for this since it is an edge case that probably requires digging very deeply into sklearn. Even if we find a fix, I have the suspicion it could easily break with an sklearn update. So possibly we should just document the easy fix from above somewhere (FAQ?) and be done with it.

**Comment by BenjaminBossan** [comment]
@dfdazac I implemented a change to `NeuralNetBinaryClassifier' that should hopefully fix your problem (#515). If you have time and are still interested, I would like to know if this PR solves your issue.
